#include "nukex/gpu/gpu_kernels.hpp"

#if NUKEX_HAS_OPENCL
#define CL_TARGET_OPENCL_VERSION 300
#include <CL/cl.h>
#include <iostream>
#include <string>

// ── Embedded kernel sources ──
// These are generated by CMake from the .cl files.
// If the generated header doesn't exist yet, provide empty fallbacks.
#if __has_include("embedded_kernels.hpp")
#include "embedded_kernels.hpp"
#else
// Fallback: define empty strings (kernels won't compile, falls back to CPU)
namespace nukex { namespace gpu { namespace kernels {
    const char* common_cl = "";
    const char* classify_weights_cl = "";
    const char* robust_stats_cl = "";
    const char* select_pixels_cl = "";
    const char* spatial_context_cl = "";
}}}
#endif
#endif

namespace nukex {

#if NUKEX_HAS_OPENCL

cl_kernel GPUKernels::build_kernel(const GPUContext& ctx,
                                    const std::string& source,
                                    const char* kernel_name) {
    // Prepend common.cl header to the kernel source
    std::string full_source = std::string(gpu::kernels::common_cl) + "\n" + source;

    const char* src = full_source.c_str();
    size_t len = full_source.size();

    cl_int err = 0;
    cl_program program = clCreateProgramWithSource(ctx.context(), 1, &src, &len, &err);
    if (err != CL_SUCCESS || !program) {
        std::cerr << "NukeX GPU: Failed to create program for " << kernel_name
                  << " (error " << err << ")\n";
        return nullptr;
    }

    cl_device_id dev = ctx.device();
    err = clBuildProgram(program, 1, &dev, "-cl-std=CL2.0", nullptr, nullptr);
    if (err != CL_SUCCESS) {
        // Get build log
        size_t log_size = 0;
        clGetProgramBuildInfo(program, dev, CL_PROGRAM_BUILD_LOG,
                              0, nullptr, &log_size);
        std::string log(log_size, '\0');
        clGetProgramBuildInfo(program, dev, CL_PROGRAM_BUILD_LOG,
                              log_size, &log[0], nullptr);
        std::cerr << "NukeX GPU: Build failed for " << kernel_name << ":\n" << log << "\n";
        clReleaseProgram(program);
        return nullptr;
    }

    cl_kernel kernel = clCreateKernel(program, kernel_name, &err);
    clReleaseProgram(program);  // Program not needed after kernel extraction

    if (err != CL_SUCCESS || !kernel) {
        std::cerr << "NukeX GPU: Failed to create kernel " << kernel_name
                  << " (error " << err << ")\n";
        return nullptr;
    }

    return kernel;
}

bool GPUKernels::compile(const GPUContext& ctx) {
    if (!ctx.is_gpu_available()) return false;

    classify_weights_ = build_kernel(ctx, gpu::kernels::classify_weights_cl,
                                      "classify_weights");
    if (!classify_weights_) return false;

    robust_stats_ = build_kernel(ctx, gpu::kernels::robust_stats_cl,
                                  "robust_stats");
    if (!robust_stats_) { release(); return false; }

    select_pixels_ = build_kernel(ctx, gpu::kernels::select_pixels_cl,
                                   "select_pixels");
    if (!select_pixels_) { release(); return false; }

    spatial_context_ = build_kernel(ctx, gpu::kernels::spatial_context_cl,
                                     "spatial_context");
    if (!spatial_context_) { release(); return false; }

    compiled_ = true;
    return true;
}

void GPUKernels::release() {
    if (classify_weights_) { clReleaseKernel(classify_weights_); classify_weights_ = nullptr; }
    if (robust_stats_)     { clReleaseKernel(robust_stats_);     robust_stats_ = nullptr; }
    if (select_pixels_)    { clReleaseKernel(select_pixels_);    select_pixels_ = nullptr; }
    if (spatial_context_)  { clReleaseKernel(spatial_context_);  spatial_context_ = nullptr; }
    compiled_ = false;
}

#else // !NUKEX_HAS_OPENCL

bool GPUKernels::compile(const GPUContext&) { return false; }
void GPUKernels::release() {}

#endif

} // namespace nukex
